-- Table: users
CREATE TABLE IF NOT EXISTS public.users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    role TEXT CHECK (role IN ('admin', 'staff', 'customer')) DEFAULT 'customer',
    phone_number TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Table: orders
CREATE TABLE IF NOT EXISTS public.orders (
    id TEXT PRIMARY KEY,
    customer_id UUID REFERENCES public.users(id),
    customer_name TEXT NOT NULL,
    phone TEXT NOT NULL,
    address TEXT,
    notes TEXT,
    items_count INTEGER DEFAULT 1,
    status TEXT DEFAULT 'Pending',
    amount NUMERIC DEFAULT 0.0,
    payment_status TEXT DEFAULT 'Unpaid',
    priority_level TEXT DEFAULT 'Standard',
    service_type TEXT DEFAULT 'General',
    assigned_staff_id UUID REFERENCES public.users(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Table: order_updates
CREATE TABLE IF NOT EXISTS public.order_updates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id TEXT NOT NULL REFERENCES public.orders(id),
    status TEXT NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Table: machinery
CREATE TABLE IF NOT EXISTS public.machinery (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    type TEXT NOT NULL,
    status TEXT DEFAULT 'Operational',
    assigned_order_id TEXT REFERENCES public.orders(id),
    cycle_start_time TIMESTAMP WITH TIME ZONE,
    expected_end_time TIMESTAMP WITH TIME ZONE,
    usage_count INTEGER DEFAULT 0,
    last_service TIMESTAMP WITH TIME ZONE,
    notes TEXT
);

-- Seed Initial Admin User
INSERT INTO public.users (email, name, role, phone_number)
VALUES ('admin@lms.com', 'System Admin', 'admin', '0000000000')
ON CONFLICT (email) DO NOTHING;

-- Seed Initial Machinery
INSERT INTO public.machinery (name, type) VALUES 
('Unit Alpha', 'Washing Machine'),
('Unit Beta', 'Washing Machine'),
('Dryer X1', 'Dryer'),
('Pulse Iron', 'Steam Iron Press');
